In [14]:
import pandas as pd

df = pd.read_csv('uber_data.csv')
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [15]:
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

In [16]:
df = df.drop_duplicates().reset_index(drop=True)
df['trip_id'] = df.index

In [17]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,trip_id
0,1,2016-03-01,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35,0
1,1,2016-03-01,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35,1
2,2,2016-03-01,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80,2
3,2,2016-03-01,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62,3
4,2,2016-03-01,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80,4

In [18]:
datetime_dim = df[['tpep_pickup_datetime','tpep_dropoff_datetime']].reset_index(drop=True)
datetime_dim['tpep_pickup_datetime'] = datetime_dim['tpep_pickup_datetime']
datetime_dim['pick_hour'] = datetime_dim['tpep_pickup_datetime'].dt.hour
datetime_dim['pick_day'] = datetime_dim['tpep_pickup_datetime'].dt.day
datetime_dim['pick_month'] = datetime_dim['tpep_pickup_datetime'].dt.month
datetime_dim['pick_year'] = datetime_dim['tpep_pickup_datetime'].dt.year
datetime_dim['pick_weekday'] = datetime_dim['tpep_pickup_datetime'].dt.weekday

datetime_dim['tpep_dropoff_datetime'] = datetime_dim['tpep_dropoff_datetime']
datetime_dim['drop_hour'] = datetime_dim['tpep_dropoff_datetime'].dt.hour
datetime_dim['drop_day'] = datetime_dim['tpep_dropoff_datetime'].dt.day
datetime_dim['drop_month'] = datetime_dim['tpep_dropoff_datetime'].dt.month
datetime_dim['drop_year'] = datetime_dim['tpep_dropoff_datetime'].dt.year
datetime_dim['drop_weekday'] = datetime_dim['tpep_dropoff_datetime'].dt.weekday

datetime_dim['datetime_id'] = datetime_dim.index
datetime_dim = datetime_dim[['datetime_id','tpep_pickup_datetime','pick_hour','pick_day','pick_month','pick_year','pick_weekday',
                            'tpep_dropoff_datetime','drop_hour','drop_day','drop_month','drop_year','drop_weekday']]
datetime_dim.head()

,datetime_id,tpep_pickup_datetime,pick_hour,pick_day,pick_month,pick_year,pick_weekday,tpep_dropoff_datetime,drop_hour,drop_day,drop_month,drop_year,drop_weekday
0,0,2016-03-01,0,1,3,2016,1,2016-03-01 00:07:55,0,1,3,2016,1
1,1,2016-03-01,0,1,3,2016,1,2016-03-01 00:11:06,0,1,3,2016,1
2,2,2016-03-01,0,1,3,2016,1,2016-03-01 00:31:06,0,1,3,2016,1
3,3,2016-03-01,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1
4,4,2016-03-01,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1

In [19]:
passenger_count_dim = df[['passenger_count']].reset_index(drop=True)
passenger_count_dim['passenger_count_id'] = passenger_count_dim.index
passenger_count_dim = passenger_count_dim[['passenger_count_id','passenger_count']]

trip_distance_dim = df[['trip_distance']].reset_index(drop=True)
trip_distance_dim['trip_distance_id'] = trip_distance_dim.index
trip_distance_dim = trip_distance_dim[['trip_distance_id','trip_distance']]

In [20]:
rate_code_type = {
    1:"Standard rate",
    2:"JFK",
    3:"Newark",
    4:"Nassau or Westchester",
    5:"Negotiated fare",
    6:"Group ride"
}

rate_code_dim = df[['RatecodeID']].reset_index(drop=True)
rate_code_dim['rate_code_id'] = rate_code_dim.index
rate_code_dim['rate_code_name'] = rate_code_dim['RatecodeID'].map(rate_code_type)
rate_code_dim = rate_code_dim[['rate_code_id','RatecodeID','rate_code_name']]
rate_code_dim.head()

   rate_code_id  RatecodeID rate_code_name
0             0           1  Standard rate
1             1           1  Standard rate
2             2           1  Standard rate
3             3           1  Standard rate
4             4           3         Newark

In [23]:
pickup_location_dim = df[['pickup_longitude','pickup_latitude']].reset_index(drop=True)
pickup_location_dim['pickup_location_id'] = pickup_location_dim.index
pickup_location_dim = pickup_location_dim[['pickup_location_id','pickup_latitude','pickup_longitude']]

dropoff_location_dim = df[['dropoff_longitude', 'dropoff_latitude']].reset_index(drop=True)
dropoff_location_dim['dropoff_location_id'] = dropoff_location_dim.index
dropoff_location_dim = dropoff_location_dim[['dropoff_location_id','dropoff_latitude','dropoff_longitude']]

In [24]:
payment_type_name = {
    1:"Credit card",
    2:"Cash",
    3:"No charge",
    4:"Dispute",
    5:"Unknown",
    6:"Voided trip"
}

payment_type_dim = df[['payment_type']].reset_index(drop=True)
payment_type_dim['payment_type_id'] = payment_type_dim.index
payment_type_dim['payment_type_name'] = payment_type_dim['payment_type'].map(payment_type_name)
payment_type_dim = payment_type_dim[['payment_type_id','payment_type','payment_type_name']]

In [25]:
fact_table = df.merge(passenger_count_dim, left_on='trip_id', right_on='passenger_count_id') \
             .merge(trip_distance_dim, left_on='trip_id', right_on='trip_distance_id') \
             .merge(rate_code_dim, left_on='trip_id', right_on='rate_code_id') \
             .merge(pickup_location_dim, left_on='trip_id', right_on='pickup_location_id') \
             .merge(dropoff_location_dim, left_on='trip_id', right_on='dropoff_location_id') \
             .merge(datetime_dim, left_on='trip_id', right_on='datetime_id') \
             .merge(payment_type_dim, left_on='trip_id', right_on='payment_type_id') \
             [['trip_id','VendorID', 'datetime_id', 'passenger_count_id',
               'trip_distance_id', 'rate_code_id', 'store_and_fwd_flag', 'pickup_location_id', 'dropoff_location_id',
               'payment_type_id', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
               'improvement_surcharge', 'total_amount']]
fact_table

,trip_id,VendorID,datetime_id,passenger_count_id,trip_distance_id,rate_code_id,store_and_fwd_flag,pickup_location_id,dropoff_location_id,payment_type_id,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,0,1,0,0,0,0,N,0,0,0,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,1,1,1,1,1,N,1,1,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2,2,2,2,2,N,2,2,2,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,3,2,3,3,3,3,N,3,3,3,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,4,2,4,4,4,4,N,4,4,4,98.0,0.0,0.0,0.00,15.50,0.3,113.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,1,99995,99995,99995,99995,N,99995,99995,99995,5.0,0.0,0.5,0.00,0.00,0.3,5.80
99996,99996,1,99996,99996,99996,99996,N,99996,99996,99996,14.0,0.0,0.5,2.00,0.00,0.3,16.80
99997,99997,1,99997,99997,99997,99997,N,99997,99997,99997,29.0,0.0,0.5,8.80,5.54,0.3,44.14
99998,99998,2,99998,99998,99998,99998,N,99998,99998,99998,5.5,0.5,0.5,1.36,0.00,0.3,8.16
99999,99999,1,99999,99999,99999,99999,N,99999,99999,99999,6.0,0.0,0.5,0.00,0.00,0.3,6.80

In [26]:
payment_type_dim.columns

Index(['payment_type_id', 'payment_type', 'payment_type_name'], dtype='object')

In [27]:
fact_table.columns

Index(['trip_id', 'VendorID', 'datetime_id', 'passenger_count_id',
       'trip_distance_id', 'rate_code_id', 'store_and_fwd_flag',
       'pickup_location_id', 'dropoff_location_id', 'payment_type_id',
       'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount'],
      dtype='object')

In [28]:
fact_table

,trip_id,VendorID,datetime_id,passenger_count_id,trip_distance_id,rate_code_id,store_and_fwd_flag,pickup_location_id,dropoff_location_id,payment_type_id,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,0,1,0,0,0,0,N,0,0,0,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,1,1,1,1,1,N,1,1,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2,2,2,2,2,N,2,2,2,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,3,2,3,3,3,3,N,3,3,3,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,4,2,4,4,4,4,N,4,4,4,98.0,0.0,0.0,0.00,15.50,0.3,113.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,1,99995,99995,99995,99995,N,99995,99995,99995,5.0,0.0,0.5,0.00,0.00,0.3,5.80
99996,99996,1,99996,99996,99996,99996,N,99996,99996,99996,14.0,0.0,0.5,2.00,0.00,0.3,16.80
99997,99997,1,99997,99997,99997,99997,N,99997,99997,99997,29.0,0.0,0.5,8.80,5.54,0.3,44.14
99998,99998,2,99998,99998,99998,99998,N,99998,99998,99998,5.5,0.5,0.5,1.36,0.00,0.3,8.16
99999,99999,1,99999,99999,99999,99999,N,99999,99999,99999,6.0,0.0,0.5,0.00,0.00,0.3,6.80

In [29]:
!pip install pandas-gbq

Collecting pandas-gbq
  Downloading pandas_gbq-0.35.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: setuptools in c:\users\nehal\anaconda3\lib\site-packages (from pandas-gbq) (80.9.0)
Collecting db-dtypes<2.0.0,>=1.1.1 (from pandas-gbq)
  Downloading db_dtypes-1.6.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.26.4 in c:\users\nehal\anaconda3\lib\site-packages (from pandas-gbq) (2.3.5)
Requirement already satisfied: pandas>=1.5.3 in c:\users\nehal\anaconda3\lib\site-packages (from pandas-gbq) (2.3.3)
Requirement already satisfied: pyarrow>=12.0.0 in c:\users\nehal\anaconda3\lib\site-packages (from pandas-gbq) (21.0.0)
Collecting pydata-google-auth>=1.5.0 (from pandas-gbq)
  Downloading pydata_google_auth-1.9.1-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: psutil>=5.9.8 in c:\users\nehal\anaconda3\lib\site-packages (from pandas-gbq) (7.0.0)
Collecting google-api-core<3.0.0,>=2.15.0 (from pandas-gbq)
  Downloading google_api_core-2.30.3-py3-none-any.whl.metadata (3.1 kB)
Collecting google-auth>=2.14.1 (from pandas-gbq)
  Downloading google_auth-2.52.0-py3-none-any.whl.metadata (5.5 kB)
Collecting google-auth-oauthlib>=0.7.0 (from pandas-gbq)
  Downloading google_auth_oauthlib-1.4.0-py3-none-any.whl.metadata (2.6 kB)
Collecting google-cloud-bigquery<4.0.0,>=3.20.0 (from pandas-gbq)
  Downloading google_cloud_bigquery-3.41.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: packaging>=22.0.0 in c:\users\nehal\anaconda3\lib\site-packages (from pandas-gbq) (25.0)
Collecting googleapis-common-protos<2.0.0,>=1.63.2 (from google-api-core<3.0.0,>=2.15.0->pandas-gbq)
  Downloading googleapis_common_protos-1.75.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in c:\users\nehal\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (5.29.3)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-api-core<3.0.0,>=2.15.0->pandas-gbq)
  Downloading proto_plus-1.28.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in c:\users\nehal\anaconda3\lib\site-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.32.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\nehal\anaconda3\lib\site-packages (from google-auth>=2.14.1->pandas-gbq) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\nehal\anaconda3\lib\site-packages (from google-auth>=2.14.1->pandas-gbq) (46.0.3)
Collecting google-cloud-core<3.0.0,>=2.4.1 (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading google_cloud_core-2.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting google-resumable-media<3.0.0,>=2.0.0 (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading google_resumable_media-2.9.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in c:\users\nehal\anaconda3\lib\site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (2.9.0.post0)
Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading grpcio-1.80.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading grpcio_status-1.80.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google-crc32c<2.0.0,>=1.0.0 (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq)
  Downloading google_crc32c-1.8.0-cp313-cp313-win_amd64.whl.metadata (1.8 kB)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\nehal\anaconda3\lib\site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (4.15.0)
Collecting protobuf<8.0.0,>=4.25.8 (from google-api-core<3.0.0,>=2.15.0->pandas-gbq)
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: pytz>=2020.1 in c:\users\nehal\anaconda3\lib\site-packages (from pandas>=1.5.3->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nehal\anaconda3\lib\site-packages (from pandas>=1.5.3->pandas-gbq) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\nehal\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nehal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nehal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nehal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nehal\anaconda3\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core<3.0.0,>=2.15.0->pandas-gbq) (2026.4.22)
Requirement already satisfied: cffi>=2.0.0 in c:\users\nehal\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (2.0.0)
Requirement already satisfied: pycparser in c:\users\nehal\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.14.1->pandas-gbq) (2.23)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib>=0.7.0->pandas-gbq)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\nehal\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.14.1->pandas-gbq) (0.6.1)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Downloading pandas_gbq-0.35.0-py3-none-any.whl (50 kB)
Downloading db_dtypes-1.6.0-py3-none-any.whl (18 kB)
Downloading google_api_core-2.30.3-py3-none-any.whl (173 kB)
Downloading google_auth-2.52.0-py3-none-any.whl (245 kB)
Downloading google_cloud_bigquery-3.41.0-py3-none-any.whl (262 kB)
Downloading google_cloud_core-2.6.0-py3-none-any.whl (29 kB)
Downloading google_resumable_media-2.9.0-py3-none-any.whl (81 kB)
Downloading google_crc32c-1.8.0-cp313-cp313-win_amd64.whl (34 kB)
Downloading googleapis_common_protos-1.75.0-py3-none-any.whl (300 kB)
Downloading grpcio-1.80.0-cp313-cp313-win_amd64.whl (4.9 MB)
   ---------------------------------------- 0.0/4.9 MB ? eta -:--:--
   -------------------------------------- - 4.7/4.9 MB 27.3 MB/s eta 0:00:01
   ---------------------------------------- 4.9/4.9 MB 21.3 MB/s  0:00:00
Downloading grpcio_status-1.80.0-py3-none-any.whl (14 kB)
Downloading proto_plus-1.28.0-py3-none-any.whl (50 kB)
Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Downloading google_auth_oauthlib-1.4.0-py3-none-any.whl (19 kB)
Downloading pydata_google_auth-1.9.1-py2.py3-none-any.whl (15 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
Installing collected packages: protobuf, oauthlib, grpcio, google-crc32c, requests-oauthlib, proto-plus, googleapis-common-protos, google-resumable-media, grpcio-status, google-auth, db-dtypes, google-auth-oauthlib, google-api-core, pydata-google-auth, google-cloud-core, google-cloud-bigquery, pandas-gbq

  Attempting uninstall: protobuf

    Found existing installation: protobuf 5.29.3

   ----------------------------------------  0/17 [protobuf]
    Uninstalling protobuf-5.29.3:
   ----------------------------------------  0/17 [protobuf]
      Successfully uninstalled protobuf-5.29.3
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   ----------------------------------------  0/17 [protobuf]
   -- -------------------------------------  1/17 [oauthlib]
   -- -------------------------------------  1/17 [oauthlib]
   -- -------------------------------------  1/17 [oauthlib]
   -- -------------------------------------  1/17 [oauthlib]
   -- -------------------------------------  1/17 [oauthlib]
   -- -------------------------------------  1/17 [oauthlib]
   -- -------------------------------------  1/17 [oauthlib]
   ---- -----------------------------------  2/17 [grpcio]
   ---- -----------------------------------  2/17 [grpcio]
   ---- -----------------------------------  2/17 [grpcio]
   ---- -----------------------------------  2/17 [grpcio]
   ---- -----------------------------------  2/17 [grpcio]
   ---- -----------------------------------  2/17 [grpcio]
   ---- -----------------------------------  2/17 [grpcio]
   ---- -----------------------------------  2/17 [grpcio]
   ------- --------------------------------  3/17 [google-crc32c]
   --------- ------------------------------  4/17 [requests-oauthlib]
   --------- ------------------------------  4/17 [requests-oauthlib]
   ----------- ----------------------------  5/17 [proto-plus]
   ----------- ----------------------------  5/17 [proto-plus]
   ----------- ----------------------------  5/17 [proto-plus]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   -------------- -------------------------  6/17 [googleapis-common-protos]
   ---------------- -----------------------  7/17 [google-resumable-media]
   ---------------- -----------------------  7/17 [google-resumable-media]
   ---------------- -----------------------  7/17 [google-resumable-media]
   ------------------ ---------------------  8/17 [grpcio-status]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   --------------------- ------------------  9/17 [google-auth]
   ----------------------- ---------------- 10/17 [db-dtypes]
   ------------------------- -------------- 11/17 [google-auth-oauthlib]
   ---------------------------- ----------- 12/17 [google-api-core]
   ---------------------------- ----------- 12/17 [google-api-core]
   ---------------------------- ----------- 12/17 [google-api-core]
   ---------------------------- ----------- 12/17 [google-api-core]
   ---------------------------- ----------- 12/17 [google-api-core]
   ---------------------------- ----------- 12/17 [google-api-core]
   ------------------------------ --------- 13/17 [pydata-google-auth]
   -------------------------------- ------- 14/17 [google-cloud-core]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ----------------------------------- ---- 15/17 [google-cloud-bigquery]
   ------------------------------------- -- 16/17 [pandas-gbq]
   ------------------------------------- -- 16/17 [pandas-gbq]
   ---------------------------------------- 17/17 [pandas-gbq]

Successfully installed db-dtypes-1.6.0 google-api-core-2.30.3 google-auth-2.52.0 google-auth-oauthlib-1.4.0 google-cloud-bigquery-3.41.0 google-cloud-core-2.6.0 google-crc32c-1.8.0 google-resumable-media-2.9.0 googleapis-common-protos-1.75.0 grpcio-1.80.0 grpcio-status-1.80.0 oauthlib-3.3.1 pandas-gbq-0.35.0 proto-plus-1.28.0 protobuf-6.33.6 pydata-google-auth-1.9.1 requests-oauthlib-2.0.0

In [30]:
fact_table.to_gbq('uber_dataset.fact_table', project_id='uber-data-project-496304', if_exists='replace')

C:\Users\nehal\AppData\Local\Temp\ipykernel_16644\1032903083.py:1: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  fact_table.to_gbq('uber_dataset.fact_table', project_id='uber-data-project-496304', if_exists='replace')

Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=262006177488-3425ks60hkk80fssi9vpohv88g6q1iqd.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery&state=CLm7OJzZfFTud9oaoBZt7xhKR3X94P&code_challenge=93YqFb7scMxuSwzT_x3jdu_17KvnbbrKZfkYxe2GrzQ&code_challenge_method=S256&prompt=consent&access_type=offline

100%|██████████| 1/1 [00:00<00:00, 1327.31it/s]

In [32]:
import pandas_gbq

pandas_gbq.to_gbq(datetime_dim, 'uber_dataset.datetime_dim', project_id='uber-data-project-496304', if_exists='replace')
pandas_gbq.to_gbq(passenger_count_dim, 'uber_dataset.passenger_count_dim', project_id='uber-data-project-496304', if_exists='replace')
pandas_gbq.to_gbq(trip_distance_dim, 'uber_dataset.trip_distance_dim', project_id='uber-data-project-496304', if_exists='replace')
pandas_gbq.to_gbq(rate_code_dim, 'uber_dataset.rate_code_dim', project_id='uber-data-project-496304', if_exists='replace')
pandas_gbq.to_gbq(pickup_location_dim, 'uber_dataset.pickup_location_dim', project_id='uber-data-project-496304', if_exists='replace')
pandas_gbq.to_gbq(dropoff_location_dim, 'uber_dataset.dropoff_location_dim', project_id='uber-data-project-496304', if_exists='replace')
pandas_gbq.to_gbq(payment_type_dim, 'uber_dataset.payment_type_dim', project_id='uber-data-project-496304', if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 2483.31it/s]
100%|██████████| 1/1 [00:00<00:00, 159.98it/s]
100%|██████████| 1/1 [00:00<00:00, 4190.11it/s]
100%|██████████| 1/1 [00:00<00:00, 4396.55it/s]
100%|██████████| 1/1 [00:00<00:00, 2732.45it/s]
100%|██████████| 1/1 [00:00<00:00, 2377.72it/s]
100%|██████████| 1/1 [00:00<00:00, 6512.89it/s]